### ISSUE TITLE
 Redefinition of PaperTrail::Version stopped working in v12/v14 with Rails 6.1 using Zeitwerk

### ISSUE THREAD

**Issue by AdrienGiboire** [paper-trail-gem/paper_trail#1421]
The [original issue](https://github.com/paper-trail-gem/paper_trail/issues/1305) has been closed but people are still reporting this to be current for the last year. I am creating a new issue to surface this issue as the original one lost visibility. It was closed because it was stated to be working with `:zeitwerk` and not with `:classic` so we should just change our `config/application.rb`. People have reported actually using `:zeitwerk`

I also can report this issue to be current still running Rails 6.1 with Zeitwerk and PT 12 & 14.

```
Loading development environment (Rails 6.1.3.2)
irb(main):001:0> Rails.application.config.autoloader
=> :zeitwerk
irb(main):002:0> Module.const_source_location("PaperTrail::Version")
=> ["/home/adrien/.gem/ruby/2.7.4/gems/paper_trail-14.0.0/lib/paper_trail/frameworks/active_record/models/paper_trail/version.rb", 13]
irb(main):003:0>
```

I have tried also including `PaperTrail::VersionConcern` but the behavior did not change a bit.

The only thing that I found working comes from [this comment](https://github.com/paper-trail-gem/paper_trail/issues/1305#issuecomment-1342956668). It consists in creating `config/initializers/paper_trail.rb` and `require "paper_trail/version"`.
