### ISSUE TITLE
Rails6.1 paper trail gem class load issue

### ISSUE THREAD

**Issue by sudhindra** [paper-trail-gem/paper_trail#1328]
we have migrated from paper_trail 12.0.0 from 11.1.0 Rails version is 6.1.4. We are seeing an issue with belong_to its not loading class, I could not find any specific change either in rails6.1 or paper_trail change doc. Any help is appreciated

- [ ]  This is not a usage question, this is a bug report
- [ ] This bug can be reproduced in the latest release of the `paper_trail` gem

```
# STEP ONE: What versions are you using?
gemfile(true) do
  ruby "2.6"
  source "https://rubygems.org"
  gem "activerecord", "6.1.4
  gem "paper_trail", "12.0.0", require: false
end
```
we have defined class like this, Same setup works fine in paper_trail 11.1.0

```
class PaperTrail::Version < ActiveRecord::Base
  include PaperTrail::VersionConcern
  belongs_to :whodidit, class_name: 'User', foreign_key: 'whodunnit'
  belongs_to :emp_info
end
rb(main):003:0>  PaperTrail::Version.last
 PaperTrail::Version Load (1.1ms)  SELECT "versions".* FROM "versions" ORDER BY "versions"."id" DESC LIMIT $1  [["LIMIT", 1]]
=> #<PaperTrail::Version id: 14987424, item_type: "......", item_id: "...", event: "create", whodunnit: "f6aa8e8c-9a39-4e8a-81e6-a20acbbc4923",  emp_info_id: "a9de8761-98a1-491f-a6b2-80a03a143d5a",........>


irb(main):004:0>  PaperTrail::Version.last.whodidit 
 PaperTrail::Version Load (14.3ms)  SELECT "versions".* FROM "versions" ORDER BY "versions"."id" DESC LIMIT $1  [["LIMIT", 1]]
Traceback (most recent call last):
       1: from (irb):4
NoMethodError (undefined method `whodidit' for #<PaperTrail::Version:0x00007f83100362f0>)
Did you mean?  whodunnit

irb(main):005:0> PaperTrail::Version.last.emp_info 
 PaperTrail::Version Load (4.3ms)  SELECT "versions".* FROM "versions" ORDER BY "versions"."id" DESC LIMIT $1  [["LIMIT", 1]]
Traceback (most recent call last):
       2: from (irb):5
       1: from (irb):5:in `rescue in irb_binding'
NoMethodError (undefined method `emp_info' for #<PaperTrail::Version:0x00007f83100aaad8>)
```

**Comment by StanBright** [comment]
Hey @sudhindra did you find a solution to your issue?

**Comment by drkelly58** [comment]
Any update on this. We have this issue too.  
I'm assuming this was broken by PR #1281 but I'm not sure why, or how to fix it.

**Comment by drkelly58** [comment]
I don't fully understand the differences, but it seems that when version 12 changed from using Engine to Railtie the ability to extend the Version class was broken.  
For my use, I was able to work around this by creating an inherited class and then using that.  

```
Module PaperTrail
  class MyVersion < Version
    include VersionConcern
    def user
      User.find_by(id: self.whodunnit.to_i)
    end
   end
end

```
Then when you need to access a version using your new class

```
current = obj.versions.current.becomes(PaperTrail::MyVersion)
user_name = current.user.name

```

**Comment by tlynam** [comment]
Does this workaround work? https://github.com/paper-trail-gem/paper_trail/pull/1330/files

**Comment by Petercopter** [comment]
I'm having the same problem with the `belongs_to` association while upgrading 11.x to 12.1. I have a `versions` table, so the workaround doesn't apply to me, but I tried it anyway, and it didn't work.

**Comment by drkelly58** [comment]
@Petercopter My scenario is also using a versions table and is not an abstract class, and it works when your extended class has a different name. My post above gives an example.

**Comment by miltzi** [comment]
We're having the same issue after upgrading to 12.1. We have a versions table and we're extending PaperTrail::Version to add both attr_accessors and a class method that can be called on a `PaperTrail::Version::ActiveRecord_Associations_CollectionProxy`. We're going to stick with 11.x for now

**Comment by Petercopter** [comment]
This is still a problem in Rails 6.1, does anyone know if that's changed in Rails 7.x? 

If I'm reading the documentation correctly, this functionality is broken https://github.com/paper-trail-gem/paper_trail#5b2-item-association

It seems like the workaround from @drkelly58 would work, but... meh...

**Comment by Petercopter** [comment]
I  believe I found the solution for Rails 6.1 and paper_trail 12.x with my use case.

I had
```
class Person < ApplicationRecord
  has_paper_trail
end


module PaperTrail
  class Version < ::ActiveRecord::Base
    include PaperTrail::VersionConcern

    belongs_to :user, foreign_key: :whodunnit, optional: true
  end
end
```
Which I changed to
```
class Version < PaperTrail::Version
  belongs_to :user, foreign_key: :whodunnit, optional: true
end

class Person < ApplicationRecord
  has_paper_trail(
    versions: {
      class_name: 'Version'
    }
  )
end
```
That makes me think I was probably doing it wrong anyway :D

**Comment by ranjithjogi88** [comment]
I have tried adding this in initializer and it worked any suggestions.

require "#{Rails.root}/app/models/version.rb" in config/initializers/paper_trail.rb
